// Compact interface and local-record tools for no-database mode.
types.car.push(['images','Vehicle images','images']);
types.customer.push(['customerImage','Customer photo','file']);
types.customer[4]=['idCardImages','ID Card Images','images'];
types.driver[9]=['idCardImages','ID Card Images','images'];
if(!navs.some(x=>x[0]==='expenses'))navs.splice(5,0,['expenses','₨','Expenses']);

function input(f,v=''){
  let [key,name,type='text']=f;
  if(type==='textarea')return `<label class="field span-all">${name}<textarea name="${key}">${v||''}</textarea></label>`;
  if(type==='file')return `<label class="field">${name}<input name="${key}" type="file" accept="image/*"></label>`;
  if(type==='images')return `<label class="field span-all">${name}<input name="${key}" type="file" accept="image/*" multiple><small>Select two or as many images as needed.</small></label>`;
  return `<label class="field">${name}<input name="${key}" type="${type}" value="${v||''}"></label>`;
}

function rentalForm(mode,copy={}){
  copy={seqNo:db.rentals.filter(x=>x.mode===mode).length+1,date:new Date().toISOString().slice(0,10),...copy};
  if(mode==='without')return withoutDriverForm(copy);
  return `<section class="form-shell"><div class="form-heading"><div><h3>${copy.id?'Edit':'Add'} With Driver rental</h3><p>Update every field, then save the record.</p></div></div><form id="rentalForm" data-mode="${mode}" data-id="${copy.id||''}"><div class="form-grid">${rentalFields.map(f=>input(f,copy[f[0]])).join('')}${customInputs('rental')}</div><div class="form-footer"><button type="button" class="secondary" id="pdfPreview">Export PDF</button><button class="primary">${copy.id?'Update':'Save'} rental</button></div></form></section>`;
}

function recordActions(kind,id){return `<div class="record-actions"><button class="tiny-btn viewRecord" data-kind="${kind}" data-id="${id}">View</button><button class="tiny-btn editRecord" data-kind="${kind}" data-id="${id}">Edit</button><button class="tiny-btn danger-btn deleteRecord" data-kind="${kind}" data-id="${id}">Delete</button></div>`}
function rentalCards(records){return records.length?records.map(x=>`<article class="record"><div class="record-head"><h3>${x.customerName||'Rental agreement'} <span class="badge">#${x.seqNo||'—'} · ${x.mode==='with'?'With Driver':'Without Driver'}</span></h3>${recordActions('rental',x.id)}</div><div class="record-details">${[['Car',x.carNo],['Customer ID',x.identityCard],['Driver',x.driver||'—'],['Pickup',x.pickupPlace],['Drop-off',x.dropupPlace],['Date',x.date],['Rent','Rs. '+(x.rent||0)],['Profit','Rs. '+(x.profit||0)]].map(a=>`<div class="detail"><small>${a[0]}</small>${a[1]||'—'}</div>`).join('')}</div></article>`).join(''):'<div class="empty">No rental records yet. Click Add to create the first one.</div>'}
function masterCards(kind,records){return records.length?records.map(x=>{let main=kind==='car'?x.carName:x.name,code=kind==='car'?x.carNumber:x.identityCard;return `<article class="record"><div class="record-head"><h3>${main||label(kind)} <span class="badge">${code||'No ID'}</span></h3>${recordActions(kind,x.id)}</div><div class="record-details">${Object.entries(x).filter(([k,v])=>!['id','idCard','idCardImages','customerPhoto','customerImage','images'].includes(k)&&v).slice(0,8).map(([k,v])=>`<div class="detail"><small>${label(k)}</small>${v}</div>`).join('')}</div></article>`}).join(''):`<div class="empty">No saved ${label(kind)}s yet.</div>`}
function masterForm(kind,copy={}){return `<section class="form-shell"><div class="form-heading"><div><h3>${copy.id?'Edit':'Add'} ${label(kind)}</h3><p>${kind==='car'?'You can select multiple vehicle photos below.':'Update the saved details below.'}</p></div></div><form class="masterForm" data-kind="${kind}" data-id="${copy.id||''}"><div class="form-grid">${types[kind].map(f=>input(f,copy[f[0]])).join('')}${customInputs(kind)}</div><div class="form-footer"><button class="primary">${copy.id?'Update':'Save'} ${label(kind)}</button></div></form></section>`}

function getList(kind){return kind==='rental'?db.rentals:db[kind+'s']}
function getRecord(kind,id){return getList(kind).find(x=>String(x.id)===String(id))}
function deleteRecord(kind,id){if(!confirm('Are you sure to delete this Record?'))return;let list=getList(kind),index=list.findIndex(x=>String(x.id)===String(id));if(index<0)return;list.splice(index,1);save();toast('Record permanently deleted');render()}
function viewRecord(kind,id){let x=getRecord(kind,id);if(!x)return;let title=kind==='rental'?'Rental record':label(kind);let details=Object.entries(x).filter(([k,v])=>k!=='id'&&v&&typeof v!=='object'&&!String(v).startsWith('data:image')).map(([k,v])=>`<div class="detail"><small>${label(k)}</small>${v}</div>`).join('');let images=[x.customerImage,x.idCard,x.customerPhoto,...(x.images||[]),...(x.idCardImages||[])].filter(Boolean).filter(v=>/^data:image\/|^https:\/\//i.test(String(v))).map(v=>`<img src="${v}" alt="Saved image">`).join('');let target=current==='add'?'#addFormArea':'#rentalFormArea';let area=$(target)||$('#view');area.innerHTML=`<section class="form-shell record-view"><div class="form-heading"><div><h3>${title}</h3><p>Saved record details</p></div><button class="secondary closeView">Close</button></div><div class="record-details">${details}</div>${images?`<div class="image-gallery">${images}</div>`:''}</section>`;$('.closeView')?.addEventListener('click',()=>render())}
function editRecord(kind,id){let x=getRecord(kind,id);if(!x)return;if(kind==='rental'){current=x.mode;render();setTimeout(()=>{$('#rentalFormArea').innerHTML=rentalForm(x.mode,x);bind()},0)}else{current='add';render();setTimeout(()=>{$('#addFormArea').innerHTML=masterForm(kind,x);bind()},0)}}

function adminObjects(){return db.objects??=(['Rental','Car','Customer','Driver'].map(x=>({key:x.toLowerCase(),label:x})))}
function branding(){return db.branding??={}}
function admin(){if(user!=='super_admin')return '<div class="empty">ADMIN1 access is required.</div>';let objects=adminObjects(),logos=branding();return `<div class="admin-grid"><section class="panel"><div class="form-heading"><h3 class="panel-title">Objects</h3></div><ul class="admin-list">${objects.map(x=>`<li><span><b>${x.label}</b><small>${(db.fields[x.key]||[]).length} fields</small></span><div class="record-actions"><button class="tiny-btn adminObject" data-object="${x.key}">Fields</button><button class="tiny-btn editObject" data-object="${x.key}">Edit</button><button class="tiny-btn danger-btn removeObject" data-object="${x.key}">Remove</button></div></li>`).join('')}</ul><form id="objectForm" class="compact-form"><h3 class="panel-title">Add object</h3><label class="field">Object name<input name="label" required placeholder="e.g. Supplier"></label><div class="form-footer"><button class="primary">Add object</button></div></form><hr><h3 class="panel-title">Change user password</h3><form id="passwordForm"><label class="field">User<select name="username"><option value="admin">admin</option><option value="admin1">ADMIN1</option></select></label><label class="field">New password<input name="password" type="password" minlength="4" required></label><div class="form-footer"><button class="primary">Change password</button></div></form></section><section class="panel"><h3 class="panel-title">Fields</h3><form id="fieldForm"><label class="field">Object<select name="object">${objects.map(x=>`<option value="${x.key}">${x.label}</option>`).join('')}</select></label><label class="field">Field label<input name="name" required placeholder="e.g. License Expiry"></label><label class="field">Field type<select name="type"><option value="text">Text</option><option value="number">Number</option><option value="date">Date</option><option value="datetime-local">Date & Time</option><option value="textarea">Long text</option><option value="image">Image Upload</option></select></label><div class="form-footer"><button class="primary">Add field</button></div></form><div id="fieldList" class="custom-field-list"><p class="login-copy">Select an object’s Fields button to edit or remove its fields.</p></div><div class="logo-manager"><h3 class="panel-title">Logo Management</h3>${[['mian','Mian Rent A Car logo'],['nurax','NuraxTech Company logo']].map(([key,title])=>`<form class="logoForm" data-logo="${key}"><label class="field">${title}<input name="logo" type="file" accept="image/*" required></label><div class="form-footer"><button class="primary">${logos[key]?'Replace':'Upload'} logo</button>${logos[key]?`<button type="button" class="danger removeLogo" data-logo="${key}">Delete logo</button>`:''}</div></form>`).join('')}</div></section></div>`}

async function saveImages(files){return Promise.all([...files].filter(f=>f.size).map(dataUrl))}
function bind(){
  $('#addTabs')?.addEventListener('click',e=>{let b=e.target.closest('[data-kind]');if(!b)return;$('#addTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));$('#addFormArea').innerHTML=masterDirectory(b.dataset.kind);bind()});
  document.querySelectorAll('.openRental').forEach(b=>b.onclick=()=>{$('#rentalFormArea').innerHTML=`<div class="form-gap"></div>${rentalForm(b.dataset.mode)}`;bind()});
  document.querySelectorAll('.directorySearch').forEach(i=>i.oninput=()=>{$('#rentalDirectory').innerHTML=rentalCards(db.rentals.filter(x=>x.mode===i.dataset.mode&&JSON.stringify(x).toLowerCase().includes(i.value.toLowerCase())));bind()});
  document.querySelectorAll('.openMaster').forEach(b=>b.onclick=()=>{$('#addFormArea').innerHTML=masterForm(b.dataset.kind);bind()});
  document.querySelectorAll('.masterSearch').forEach(i=>i.oninput=()=>{$('.masterRecords').innerHTML=masterCards(i.dataset.kind,db[i.dataset.kind+'s'].filter(x=>JSON.stringify(x).toLowerCase().includes(i.value.toLowerCase())));bind()});
  document.querySelectorAll('.viewRecord').forEach(b=>b.onclick=()=>viewRecord(b.dataset.kind,b.dataset.id));
  document.querySelectorAll('.editRecord').forEach(b=>b.onclick=()=>editRecord(b.dataset.kind,b.dataset.id));
  document.querySelectorAll('.deleteRecord').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.kind,b.dataset.id));
  $('#rentalForm')?.addEventListener('submit',async e=>{e.preventDefault();let form=e.currentTarget,old=getRecord('rental',form.dataset.id)||{},fd=new FormData(form),o={...old};for(let [k,v] of fd.entries())if(!(v instanceof File))o[k]=v;for(let [k,v] of fd.entries())if(v instanceof File&&v.size)o[k]=await dataUrl(v);o.profit=(+o.rent||0)-(+o.fuelExpense||0)-(+o.toll||0)-(+o.driverCommission||0);o.id=old.id||Date.now();o.mode=form.dataset.mode;let list=db.rentals,index=list.findIndex(x=>x.id===o.id);if(index>-1)list[index]=o;else list.push(o);save();toast('Rental record saved');render()});
  $('.masterForm')?.addEventListener('submit',async e=>{e.preventDefault();let form=e.currentTarget,kind=form.dataset.kind,old=getRecord(kind,form.dataset.id)||{},fd=new FormData(form),o={...old};for(let [k,v] of fd.entries())if(!(v instanceof File))o[k]=v;for(let [k,v] of fd.entries())if(v instanceof File&&v.size&&!['images','idCardImages'].includes(k))o[k]=await dataUrl(v);for(let key of ['images','idCardImages']){let pictures=await saveImages(fd.getAll(key));if(pictures.length)o[key]=pictures}o.id=old.id||Date.now();let list=db[kind+'s'],index=list.findIndex(x=>x.id===o.id);if(index>-1)list[index]=o;else list.push(o);save();toast(`${label(kind)} saved`);$('#addFormArea').innerHTML=masterDirectory(kind);bind()});
  $('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.currentTarget)),token=localStorage.getItem('mianToken'),r=await fetch('/api/auth/password',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(data)}),out=await r.json();if(!r.ok)return toast(out.message||'Password could not be changed');e.currentTarget.reset();toast(`${data.username==='admin1'?'ADMIN1':'admin'} password changed`)});
  wireAdmin();
  if(current==='dashboard')wireDashboard();
  bindSearch();
}

function exportExcel(kind,q){let rows=db.rentals.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));if(!rows.length)return toast('Nothing to export');let headers=['Record #','Rental Type','Date','Customer','Phone','Identity Card','Car No','Driver','Pickup','Drop-off','Rent (Rs.)','Profit (Rs.)'];let data=rows.map(x=>[x.seqNo,x.mode==='with'?'With Driver':'Without Driver',x.date,x.customerName,x.phone,x.identityCard,x.carNo,x.driver,x.pickupPlace,x.dropupPlace,+x.rent||0,+x.profit||0]);let ws=XLSX.utils.aoa_to_sheet([['Mian Rent A Car — Rental Records'],[`Exported: ${new Date().toLocaleString()}`],[],headers,...data]);ws['!merges']=[XLSX.utils.decode_range('A1:L1'),XLSX.utils.decode_range('A2:L2')];ws['!cols']=headers.map((h,i)=>({wch:Math.max(h.length+2,...data.map(r=>String(r[i]||'').length+2),12)}));ws['!autofilter']={ref:`A4:L${data.length+4}`};for(let c=0;c<headers.length;c++){let cell=ws[XLSX.utils.encode_cell({r:3,c})];cell.s={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'2457E6'}},alignment:{horizontal:'center'}}}let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Rental Records');XLSX.writeFile(wb,`${kind}-rental-records.xlsx`);toast('Formatted Excel file exported')}
function showResults(kind,q){q=q.toLowerCase();let entities=db[kind+'s'].filter(x=>JSON.stringify(x).toLowerCase().includes(q)),rentals=db.rentals.filter(x=>kind==='car'?(x.carNo||'').toLowerCase().includes(q):kind==='customer'?((x.identityCard||'').toLowerCase().includes(q)||(x.customerName||'').toLowerCase().includes(q)):((x.driver||'').toLowerCase().includes(q)));let el=$('#searchResults');el.innerHTML=(entities.length?`<h3 class="panel-title">Saved ${label(kind)}s</h3>${masterCards(kind,entities)}`:'')+(rentals.length?`<h3 class="panel-title">Related rental history</h3>${rentalCards(rentals)}`:'')||'<div class="empty">No matching saved records found.</div>';document.querySelectorAll('.viewRecord').forEach(b=>b.onclick=()=>viewRecord(b.dataset.kind,b.dataset.id));document.querySelectorAll('.editRecord').forEach(b=>b.onclick=()=>editRecord(b.dataset.kind,b.dataset.id));document.querySelectorAll('.deleteRecord').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.kind,b.dataset.id))}
function showFields(object){let list=$('#fieldList');if(!list)return;let fields=db.fields[object]||[],objectName=adminObjects().find(x=>x.key===object)?.label||label(object);list.innerHTML=`<h3 class="panel-title">${objectName} fields</h3>`+(fields.length?fields.map((x,i)=>`<div class="admin-field"><span><b>${x.name}</b><small>${x.type}</small></span><div class="record-actions"><button class="tiny-btn editField" data-object="${object}" data-index="${i}">Edit</button><button class="tiny-btn danger-btn removeField" data-object="${object}" data-index="${i}">Remove</button></div></div>`).join(''):'<p class="login-copy">No fields yet.</p>');list.querySelectorAll('.editField').forEach(b=>b.onclick=()=>{let x=db.fields[b.dataset.object][+b.dataset.index],name=prompt('Field name',x.name);if(name===null||!name.trim())return;let type=prompt('Field type (text, number, date, textarea, image)',x.type);if(type===null||!type.trim())return;x.name=name.trim();x.type=type.trim();x.key=x.name.toLowerCase().replace(/\W+/g,'_');save();showFields(b.dataset.object);toast('Field updated')});list.querySelectorAll('.removeField').forEach(b=>b.onclick=()=>{if(!confirm('Remove this field?'))return;db.fields[b.dataset.object].splice(+b.dataset.index,1);save();showFields(b.dataset.object);toast('Field removed')})}
function wireAdmin(){
  $('#objectForm')?.addEventListener('submit',e=>{e.preventDefault();let label=new FormData(e.currentTarget).get('label').trim(),key=label.toLowerCase().replace(/\W+/g,'_');if(adminObjects().some(x=>x.key===key))return toast('This object already exists');adminObjects().push({key,label});db.fields[key]??=[];save();render();toast('Object added')});
  document.querySelectorAll('.adminObject').forEach(b=>b.onclick=()=>showFields(b.dataset.object));
  document.querySelectorAll('.editObject').forEach(b=>b.onclick=()=>{let x=adminObjects().find(x=>x.key===b.dataset.object),label=prompt('Object name',x.label);if(label===null||!label.trim())return;x.label=label.trim();save();render();toast('Object updated')});
  document.querySelectorAll('.removeObject').forEach(b=>b.onclick=()=>{let objects=adminObjects(),i=objects.findIndex(x=>x.key===b.dataset.object);if(i<0||!confirm('Remove this object and its custom fields?'))return;delete db.fields[b.dataset.object];objects.splice(i,1);save();render();toast('Object removed')});
  $('#fieldForm')?.addEventListener('submit',e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.currentTarget));x.key=x.name.toLowerCase().replace(/\W+/g,'_');(db.fields[x.object]??=[]).push(x);save();showFields(x.object);e.target.reset();toast('Field added')});
  document.querySelectorAll('.logoForm').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();let file=new FormData(form).get('logo');if(!file?.size)return;branding()[form.dataset.logo]=await dataUrl(file);save();applyBranding();render();toast('Logo saved')}));
  document.querySelectorAll('.removeLogo').forEach(b=>b.onclick=()=>{if(!confirm('Delete this logo?'))return;delete branding()[b.dataset.logo];save();applyBranding();render();toast('Logo deleted')});
}
function applyBranding(){let logos=branding(),mian=logos.mian,nurax=logos.nurax,marks=document.querySelectorAll('.brand-mark,.mini-mark'),company=$('#companyLogo');marks.forEach(mark=>{mark.innerHTML=mian?`<img src="${mian}" alt="Mian Rent A Car logo">`:'MR'});if(nurax){company.src=nurax;company.classList.remove('hidden')}else{company.removeAttribute('src');company.classList.add('hidden')}}
function setup(){applyBranding();$('#nav').innerHTML=navs.filter(n=>!['admin','trash'].includes(n[0])||user==='super_admin').map(n=>`<button class="nav-btn ${n[0]===current?'active':''}" data-page="${n[0]}"><i>${n[1]}</i><span>${n[2]}</span></button>`).join('');$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b){current=b.dataset.page;render()}};render()}

let dashboardFilter={period:'30',car:'',driver:''};
function money(value){return `Rs. ${(Number(value)||0).toLocaleString()}`}
function filteredRentals(){let days=+dashboardFilter.period,now=new Date(),start=new Date(now);if(days)start.setDate(now.getDate()-days+1);return db.rentals.filter(r=>{let date=new Date(`${r.date||''}T00:00:00`);return (!days||(!Number.isNaN(date)&&date>=start&&date<=now))&&(!dashboardFilter.car||r.carNo===dashboardFilter.car)&&(!dashboardFilter.driver||r.driver===dashboardFilter.driver)})}
function totals(records){return records.reduce((sum,r)=>{let sales=+r.rent||0,costs=(+r.fuelExpense||0)+(+r.toll||0)+(+r.driverCommission||0),profit=r.profit!==undefined?+r.profit:sales-costs;sum.sales+=sales;sum.costs+=costs;sum.profit+=profit;sum.trips++;return sum},{sales:0,costs:0,profit:0,trips:0})}
function analyticsHtml(){let records=filteredRentals(),total=totals(records),cars=[...new Set(db.rentals.map(r=>r.carNo).filter(Boolean))],drivers=[...new Set(db.rentals.map(r=>r.driver).filter(Boolean))];let byCar=cars.map(car=>({name:car,...totals(records.filter(r=>r.carNo===car))})).filter(x=>x.trips),byDriver=drivers.map(driver=>{let rows=records.filter(r=>r.driver===driver),t=totals(rows);return {name:driver,...t,commission:rows.reduce((n,r)=>n+(+r.driverCommission||0),0)}}).filter(x=>x.trips);return `<section class="panel performance-panel"><div class="form-heading"><div><h3 class="panel-title">Sales, Profit & Loss Report</h3><p>Filter by period, car, or driver to see business performance.</p></div></div><div class="analytics-filters"><div class="period-buttons">${[['20','Last 20 days'],['30','Last 30 days'],['60','Last 2 months'],['120','Last 4 months'],['0','All time']].map(([value,text])=>`<button class="object-tab periodFilter ${dashboardFilter.period===value?'active':''}" data-period="${value}">${text}</button>`).join('')}</div><label class="field">Car<select id="dashboardCar"><option value="">All cars</option>${cars.map(x=>`<option value="${x}" ${dashboardFilter.car===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Driver<select id="dashboardDriver"><option value="">All drivers</option>${drivers.map(x=>`<option value="${x}" ${dashboardFilter.driver===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="analytics-stats"><div><small>Total sales</small><b>${money(total.sales)}</b></div><div><small>Total expenses</small><b>${money(total.costs)}</b></div><div><small>Net profit</small><b class="${total.profit<0?'loss':'profit'}">${money(total.profit)}</b></div><div><small>Loss</small><b class="loss">${money(Math.max(0,-total.profit))}</b></div><div><small>Rental trips</small><b>${total.trips}</b></div></div><div class="performance-grid"><div><h3 class="panel-title">Car-wise performance</h3>${performanceTable(byCar,'car')}</div><div><h3 class="panel-title">Driver-wise performance</h3>${driverTable(byDriver)}</div></div></section>`}
function performanceTable(rows){return rows.length?`<div class="performance-table"><div class="performance-head"><span>Car</span><span>Trips</span><span>Sales</span><span>Expenses</span><span>Profit</span></div>${rows.map(x=>`<div class="performance-row"><b>${x.name}</b><span>${x.trips}</span><span>${money(x.sales)}</span><span>${money(x.costs)}</span><span class="${x.profit<0?'loss':'profit'}">${money(x.profit)}</span></div>`).join('')}</div>`:'<p class="login-copy">No car rentals match this filter.</p>'}
function driverTable(rows){return rows.length?`<div class="performance-table driver-table"><div class="performance-head"><span>Driver</span><span>Trips</span><span>Sales</span><span>Commission</span><span>Profit</span></div>${rows.map(x=>`<div class="performance-row"><b>${x.name}</b><span>${x.trips}</span><span>${money(x.sales)}</span><span>${money(x.commission)}</span><span class="${x.profit<0?'loss':'profit'}">${money(x.profit)}</span></div>`).join('')}</div>`:'<p class="login-copy">No driver rentals match this filter.</p>'}
function dashboard(){let all=totals(db.rentals);return `<div class="stats">${[['Total Cars',db.cars.length,'🚘','#eaf0ff'],['Total Rentals',db.rentals.length,'▤','#e8fbf4'],['Total Drivers',db.drivers.length,'♟','#fff3e8'],['Total Sales',money(all.sales),'↗','#f4edff']].map(x=>`<div class="stat"><div class="stat-top"><span>${x[0]}</span><b class="stat-icon" style="background:${x[3]}">${x[2]}</b></div><h3>${x[1]}</h3><p>Current saved records</p></div>`).join('')}</div><div class="chart-grid"><div class="panel"><h3 class="panel-title">Rental income overview</h3><canvas id="incomeChart" height="115"></canvas></div><div class="panel"><h3 class="panel-title">Business summary</h3><div class="summary-row"><span>Total sales</span><b>${money(all.sales)}</b></div><div class="summary-row"><span>Operating expenses</span><b>${money(all.costs)}</b></div><div class="summary-row"><span>Recorded profit</span><b>${money(all.profit)}</b></div><div class="summary-row"><span>With driver</span><b>${db.rentals.filter(x=>x.mode==='with').length}</b></div></div></div>${analyticsHtml()}`}
function wireDashboard(){document.querySelectorAll('.periodFilter').forEach(b=>b.onclick=()=>{dashboardFilter.period=b.dataset.period;render()});$('#dashboardCar')?.addEventListener('change',e=>{dashboardFilter.car=e.target.value;render()});$('#dashboardDriver')?.addEventListener('change',e=>{dashboardFilter.driver=e.target.value;render()});if(window.Chart&&$('#incomeChart')){let monthly=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map((label,index)=>({label,income:db.rentals.filter(r=>new Date(r.date).getMonth()===index).reduce((n,r)=>n+(+r.rent||0),0)}));new Chart($('#incomeChart'),{type:'bar',data:{labels:monthly.map(x=>x.label),datasets:[{data:monthly.map(x=>x.income),backgroundColor:'#2457e6',borderRadius:5}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}})}}

function expenseRows(){return db.expenses??=[]}
function expenseAmount(car=''){let days=+dashboardFilter.period,now=new Date(),start=new Date(now);if(days)start.setDate(now.getDate()-days+1);return expenseRows().filter(x=>{let date=new Date(`${x.date||''}T00:00:00`);return (!days||(!Number.isNaN(date)&&date>=start&&date<=now))&&(!car||x.carNo===car)}).reduce((n,x)=>n+(+x.amount||0),0)}
function expenses(){return `<section class="panel"><div class="form-heading"><div><h3 class="panel-title">Expenses</h3><p>Car expenses automatically reduce that car’s profit. All expenses are included in business profit and loss.</p></div></div><div class="expense-actions">${[['car','Car Expense'],['rent','Rent Expense'],['food','Food Expense'],['other','Other Expense']].map(x=>`<button class="primary" onclick="openExpense('${x[0]}')">${x[1]}</button>`).join('')}</div><div id="expenseFormArea"></div><div class="expense-list"><h3 class="panel-title">Saved expenses</h3>${expenseRows().length?expenseRows().slice().reverse().map(x=>`<article class="record"><div class="record-head"><h3>${label(x.type)} Expense <span class="badge">${money(x.amount)}</span></h3><button class="tiny-btn danger-btn" onclick="deleteExpense(${x.id})">Delete</button></div><div class="record-details">${[['Date',x.date],['Time',x.time],['Car',x.carNo],['Person',x.person||x.receivingPerson],['Reason',x.reason],['Notes',x.notes]].filter(x=>x[1]).map(x=>`<div class="detail"><small>${x[0]}</small>${x[1]}</div>`).join('')}</div></article>`).join(''):'<p class="login-copy">No expense saved yet.</p>'}</div></section>`}
function openExpense(type){let today=new Date().toISOString().slice(0,10),cars=db.cars||[],fields=type==='car'?`<label class="field">Car Number<select name="carNo" required><option value="">Select car</option>${cars.map(x=>`<option value="${x.carNumber||x.registrationNumber}">${x.carNumber||x.registrationNumber}</option>`).join('')}</select></label><label class="field">Person Name<input name="person" required></label><label class="field">Amount<input name="amount" type="number" min="0" required></label><label class="field">Reason of Expense<select name="reason" onchange="toggleOtherExpense(this.value)" required><option>Oil change</option><option>Damage issue</option><option>Tire problem</option><option>Other</option></select></label><label id="otherExpenseNotes" class="field span-all hidden">Notes<textarea name="notes" placeholder="Add notes for other reason"></textarea></label>`:type==='rent'?`<label class="field">Date<input name="date" type="date" value="${today}" required></label><label class="field">Time<input name="time" type="time" required></label><label class="field">Receiving Person<input name="receivingPerson" required></label><label class="field">Amount<input name="amount" type="number" min="0" required></label><label class="field span-all">Notes (optional)<textarea name="notes"></textarea></label>`:type==='food'?`<label class="field">Date<input name="date" type="date" value="${today}" required></label><label class="field">Time<input name="time" type="time" required></label><label class="field">Amount<input name="amount" type="number" min="0" required></label><label class="field span-all">Notes (optional)<textarea name="notes"></textarea></label>`:`<label class="field">Amount<input name="amount" type="number" min="0" required></label><label class="field span-all">Notes<input name="notes" required placeholder="Reason for other expense"></label>`;$('#expenseFormArea').innerHTML=`<section class="form-shell expense-form"><div class="form-heading"><h3>${label(type)} Expense</h3><button class="secondary" type="button" onclick="closeExpense()">Close</button></div><form data-type="${type}" onsubmit="saveExpense(event,this)"><div class="form-grid">${fields}</div><div class="form-footer"><button class="primary">Save expense</button></div></form></section>`}
function closeExpense(){$('#expenseFormArea').innerHTML=''}
function toggleOtherExpense(value){$('#otherExpenseNotes')?.classList.toggle('hidden',value!=='Other')}
function saveExpense(event,form){event.preventDefault();let x=Object.fromEntries(new FormData(form));x.id=Date.now();x.type=form.dataset.type;x.date=x.date||new Date().toISOString().slice(0,10);x.amount=+x.amount||0;expenseRows().push(x);save();toast('Expense saved');render()}
function deleteExpense(id){if(!confirm('Are you sure to delete this Expense?'))return;let i=expenseRows().findIndex(x=>x.id===id);if(i>-1){expenseRows().splice(i,1);save();toast('Expense deleted');render()}}
function analyticsHtml(){let records=filteredRentals(),total=totals(records),extra=expenseAmount(dashboardFilter.car);total.costs+=extra;total.profit-=extra;let cars=[...new Set(db.rentals.map(r=>r.carNo).filter(Boolean))],drivers=[...new Set(db.rentals.map(r=>r.driver).filter(Boolean))];let byCar=cars.map(car=>{let t=totals(records.filter(r=>r.carNo===car)),cost=expenseAmount(car);t.costs+=cost;t.profit-=cost;return {name:car,...t}}).filter(x=>x.trips),byDriver=drivers.map(driver=>{let rows=records.filter(r=>r.driver===driver),t=totals(rows);return {name:driver,...t,commission:rows.reduce((n,r)=>n+(+r.driverCommission||0),0)}}).filter(x=>x.trips);return `<section class="panel performance-panel"><div class="form-heading"><div><h3 class="panel-title">Sales, Profit & Loss Report</h3><p>Expenses are included in profit and loss totals.</p></div></div><div class="analytics-filters"><div class="period-buttons">${[['20','Last 20 days'],['30','Last 30 days'],['60','Last 2 months'],['120','Last 4 months'],['0','All time']].map(x=>`<button class="object-tab periodFilter ${dashboardFilter.period===x[0]?'active':''}" data-period="${x[0]}">${x[1]}</button>`).join('')}</div><label class="field">Car<select id="dashboardCar"><option value="">All cars</option>${cars.map(x=>`<option value="${x}" ${dashboardFilter.car===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Driver<select id="dashboardDriver"><option value="">All drivers</option>${drivers.map(x=>`<option value="${x}" ${dashboardFilter.driver===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="analytics-stats"><div><small>Total sales</small><b>${money(total.sales)}</b></div><div><small>Total expenses</small><b>${money(total.costs)}</b></div><div><small>Net profit</small><b class="${total.profit<0?'loss':'profit'}">${money(total.profit)}</b></div><div><small>Loss</small><b class="loss">${money(Math.max(0,-total.profit))}</b></div><div><small>Rental trips</small><b>${total.trips}</b></div></div><div class="performance-grid"><div><h3 class="panel-title">Car-wise performance</h3>${performanceTable(byCar)}</div><div><h3 class="panel-title">Driver-wise performance</h3>${driverTable(byDriver)}</div></div></section>`}
function dashboard(){let all=totals(db.rentals),extra=expenseAmount();all.costs+=extra;all.profit-=extra;return `<div class="stats">${[['Total Cars',db.cars.length,'🚘','#eaf0ff'],['Total Rentals',db.rentals.length,'▤','#e8fbf4'],['Total Drivers',db.drivers.length,'♟','#fff3e8'],['Total Sales',money(all.sales),'↗','#f4edff']].map(x=>`<div class="stat"><div class="stat-top"><span>${x[0]}</span><b class="stat-icon" style="background:${x[3]}">${x[2]}</b></div><h3>${x[1]}</h3><p>Current saved records</p></div>`).join('')}</div><div class="chart-grid"><div class="panel"><h3 class="panel-title">Rental income overview</h3><canvas id="incomeChart" height="115"></canvas></div><div class="panel"><h3 class="panel-title">Business summary</h3><div class="summary-row"><span>Total sales</span><b>${money(all.sales)}</b></div><div class="summary-row"><span>Operating expenses</span><b>${money(all.costs)}</b></div><div class="summary-row"><span>Recorded profit</span><b>${money(all.profit)}</b></div><div class="summary-row"><span>With driver</span><b>${db.rentals.filter(x=>x.mode==='with').length}</b></div></div></div>${analyticsHtml()}`}
function render(){let titles={dashboard:['OVERVIEW','Dashboard'],without:['RENTAL AGREEMENT','Without Driver'],with:['RENTAL AGREEMENT','With Driver'],search:['FIND RECORDS','Search Data'],add:['MASTER DATA','Add Data'],expenses:['BUSINESS COSTS','Expenses'],trash:['RECORD SAFETY','Trash'],admin:['SYSTEM CONFIGURATION','Admin Setup']};$('#pageKicker').textContent=titles[current][0];$('#pageTitle').textContent=titles[current][1];[...document.querySelectorAll('.nav-btn')].forEach(x=>x.classList.toggle('active',x.dataset.page===current));let f={dashboard,without:()=>rentalHub('without'),with:withDriver,search,add:addData,expenses,trash,admin}[current];$('#view').innerHTML=f();bind()}

let exportSaving=false;
async function exportLocalData(){if(exportSaving)return;let token=localStorage.getItem('mianToken');if(!token)return;exportSaving=true;try{await fetch('/api/export/state',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({state:db})})}catch{console.warn('Local folder export is unavailable.')}finally{exportSaving=false}}
function save(){localStorage.setItem('mianRac',JSON.stringify(db));pendingSave++;persistState();exportLocalData()}
